from django.urls import path

from .views import (
    AlertListView,
    AlertStatusUpdateView,
    CaptureLabelView,
    ColdPointDetailView,
    ColdPointListCreateView,
    ColdSectorDetailView,
    ColdSectorListCreateView,
    DraftLotListView,
    FicheImportView,
    LotReportCsvView,
    LotReportPdfView,
    ReconcileIdenticalLotsView,
    LotTransformView,
    LotValidateView,
    MeView,
    SiteListCreateView,
    TemperatureConfirmView,
    TemperatureCaptureView,
    TemperatureRegisterCsvView,
    TemperatureReadingListView,
    TemperatureRouteListCreateView,
    TemperatureRouteSequenceView,
    TemperatureRouteStepListCreateView,
    TokenLoginView,
    debug_env,
)

urlpatterns = [
    path("debug/env", debug_env, name="debug-env"),
    path("auth/token", TokenLoginView.as_view(), name="auth-token"),
    path("auth/me", MeView.as_view(), name="auth-me"),
    path("sites", SiteListCreateView.as_view(), name="site-list-create"),
    path("import/fiches", FicheImportView.as_view(), name="fiches-import"),
    path("capture/label-photo", CaptureLabelView.as_view(), name="capture-label-photo"),
    path("cold-sectors", ColdSectorListCreateView.as_view(), name="cold-sector-list-create"),
    path("cold-sectors/<uuid:sector_id>", ColdSectorDetailView.as_view(), name="cold-sector-detail"),
    path("cold-points", ColdPointListCreateView.as_view(), name="cold-point-list-create"),
    path("cold-points/<uuid:point_id>", ColdPointDetailView.as_view(), name="cold-point-detail"),
    path("temperature-routes", TemperatureRouteListCreateView.as_view(), name="temperature-route-list-create"),
    path("temperature-routes/steps", TemperatureRouteStepListCreateView.as_view(), name="temperature-route-step-list-create"),
    path("temperature-routes/<uuid:route_id>/sequence", TemperatureRouteSequenceView.as_view(), name="temperature-route-sequence"),
    path("temperatures/capture", TemperatureCaptureView.as_view(), name="temperature-capture"),
    path("temperatures/capture-preview", TemperatureCaptureView.as_view(), name="temperature-capture-preview"),
    path("temperatures/confirm", TemperatureConfirmView.as_view(), name="temperature-confirm"),
    path("temperatures", TemperatureReadingListView.as_view(), name="temperature-list"),
    path("lots/drafts", DraftLotListView.as_view(), name="lots-drafts"),
    path("lots/reconcile-identical", ReconcileIdenticalLotsView.as_view(), name="lots-reconcile-identical"),
    path("lots/<uuid:lot_id>/validate", LotValidateView.as_view(), name="lot-validate"),
    path("lots/<uuid:lot_id>/transform", LotTransformView.as_view(), name="lot-transform"),
    path("alerts", AlertListView.as_view(), name="alerts-list"),
    path("alerts/<uuid:alert_id>/status", AlertStatusUpdateView.as_view(), name="alerts-status-update"),
    path("reports/lots.csv", LotReportCsvView.as_view(), name="report-lots-csv"),
    path("reports/lots.pdf", LotReportPdfView.as_view(), name="report-lots-pdf"),
    path("reports/temperatures.csv", TemperatureRegisterCsvView.as_view(), name="report-temperatures-csv"),
]
