from django.urls import path

from .haccp_views import (
    HaccpAssetDownloadView,
    HaccpAssetListView,
    HaccpColdPointDetailView,
    HaccpColdPointListView,
    HaccpColdPointSyncView,
    HaccpLabelProfileDetailView,
    HaccpLabelProfileListCreateView,
    HaccpLabelSessionListCreateView,
    HaccpLifecycleEventListView,
    HaccpOcrResultListView,
    HaccpOcrResultValidateView,
    HaccpTraceabilityValidationUpsertView,
    HaccpScheduleDetailView,
    HaccpScheduleListCreateView,
    HaccpTemperatureReadingListView,
    HaccpSectorDetailView,
    HaccpSectorListView,
    HaccpSectorSyncView,
    HaccpSiteListView,
    HaccpSiteSyncView,
)
from .cookops_inventory_views import (
    InventoryProductListView,
    InventorySectorListView,
    InventorySessionCloseView,
    InventorySessionDetailView,
    InventorySessionLinesBulkUpsertView,
    InventorySessionListCreateView,
    InventoryStockPointListView,
    InventorySupplierListView,
)
from .views import (
    AlertListView,
    AlertStatusUpdateView,
    CaptureLabelView,
    ColdPointDetailView,
    ColdPointListCreateView,
    ColdSectorDetailView,
    ColdSectorListCreateView,
    ActiveLotSearchView,
    FicheImportView,
    LabelPrintView,
    LabelProfileDetailView,
    LabelProfileListCreateView,
    LotReportCsvView,
    LotReportPdfView,
    ReconcileIdenticalLotsView,
    MeView,
    SiteListCreateView,
    TemperatureConfirmView,
    TemperatureCaptureView,
    TemperatureRegisterCsvView,
    TemperatureReadingListView,
    TemperatureRouteListCreateView,
    TemperatureRouteSequenceView,
    TemperatureRouteStepListCreateView,
    TokenLoginView,
    debug_env,
)

urlpatterns = [
    path("v1/haccp/sites/", HaccpSiteListView.as_view(), name="haccp-site-list"),
    path("v1/haccp/sites/sync/", HaccpSiteSyncView.as_view(), name="haccp-site-sync"),
    path("v1/haccp/assets/", HaccpAssetListView.as_view(), name="haccp-asset-list"),
    path("v1/haccp/assets/<uuid:asset_id>/download/", HaccpAssetDownloadView.as_view(), name="haccp-asset-download"),
    path("v1/haccp/sectors/", HaccpSectorListView.as_view(), name="haccp-sector-list"),
    path("v1/haccp/sectors/<uuid:sector_id>/", HaccpSectorDetailView.as_view(), name="haccp-sector-detail"),
    path("v1/haccp/sectors/sync/", HaccpSectorSyncView.as_view(), name="haccp-sector-sync"),
    path("v1/haccp/cold-points/", HaccpColdPointListView.as_view(), name="haccp-cold-point-list"),
    path("v1/haccp/cold-points/<uuid:point_id>/", HaccpColdPointDetailView.as_view(), name="haccp-cold-point-detail"),
    path("v1/haccp/cold-points/sync/", HaccpColdPointSyncView.as_view(), name="haccp-cold-point-sync"),
    path("v1/haccp/temperature-readings/", HaccpTemperatureReadingListView.as_view(), name="haccp-temperature-reading-list"),
    path("v1/haccp/schedules/", HaccpScheduleListCreateView.as_view(), name="haccp-schedule-list-create"),
    path("v1/haccp/schedules/<uuid:schedule_id>/", HaccpScheduleDetailView.as_view(), name="haccp-schedule-detail"),
    path("v1/haccp/ocr-results/", HaccpOcrResultListView.as_view(), name="haccp-ocr-results"),
    path("v1/haccp/ocr-results/<uuid:document_id>/validate/", HaccpOcrResultValidateView.as_view(), name="haccp-ocr-validate"),
    path("v1/haccp/traceability-validations/", HaccpTraceabilityValidationUpsertView.as_view(), name="haccp-traceability-validation-upsert"),
    path("v1/haccp/lifecycle-events/", HaccpLifecycleEventListView.as_view(), name="haccp-lifecycle-events"),
    path("v1/haccp/label-profiles/", HaccpLabelProfileListCreateView.as_view(), name="haccp-label-profile-list-create"),
    path("v1/haccp/label-profiles/<uuid:profile_id>/", HaccpLabelProfileDetailView.as_view(), name="haccp-label-profile-detail"),
    path("v1/haccp/label-sessions/", HaccpLabelSessionListCreateView.as_view(), name="haccp-label-session-list-create"),
    path("inventory/suppliers", InventorySupplierListView.as_view(), name="inventory-supplier-list"),
    path("inventory/sectors", InventorySectorListView.as_view(), name="inventory-sector-list"),
    path("inventory/stock-points", InventoryStockPointListView.as_view(), name="inventory-stock-point-list"),
    path("inventory/products", InventoryProductListView.as_view(), name="inventory-product-list"),
    path("inventory/sessions", InventorySessionListCreateView.as_view(), name="inventory-session-list-create"),
    path("inventory/sessions/<uuid:session_id>", InventorySessionDetailView.as_view(), name="inventory-session-detail"),
    path("inventory/sessions/<uuid:session_id>/lines/bulk-upsert", InventorySessionLinesBulkUpsertView.as_view(), name="inventory-session-lines-bulk-upsert"),
    path("inventory/sessions/<uuid:session_id>/close", InventorySessionCloseView.as_view(), name="inventory-session-close"),
    path("debug/env", debug_env, name="debug-env"),
    path("auth/token", TokenLoginView.as_view(), name="auth-token"),
    path("auth/me", MeView.as_view(), name="auth-me"),
    path("sites", SiteListCreateView.as_view(), name="site-list-create"),
    path("import/fiches", FicheImportView.as_view(), name="fiches-import"),
    path("capture/label-photo", CaptureLabelView.as_view(), name="capture-label-photo"),
    path("cold-sectors", ColdSectorListCreateView.as_view(), name="cold-sector-list-create"),
    path("cold-sectors/<uuid:sector_id>", ColdSectorDetailView.as_view(), name="cold-sector-detail"),
    path("cold-points", ColdPointListCreateView.as_view(), name="cold-point-list-create"),
    path("cold-points/<uuid:point_id>", ColdPointDetailView.as_view(), name="cold-point-detail"),
    path("temperature-routes", TemperatureRouteListCreateView.as_view(), name="temperature-route-list-create"),
    path("temperature-routes/steps", TemperatureRouteStepListCreateView.as_view(), name="temperature-route-step-list-create"),
    path("temperature-routes/<uuid:route_id>/sequence", TemperatureRouteSequenceView.as_view(), name="temperature-route-sequence"),
    path("temperatures/capture", TemperatureCaptureView.as_view(), name="temperature-capture"),
    path("temperatures/capture-preview", TemperatureCaptureView.as_view(), name="temperature-capture-preview"),
    path("temperatures/confirm", TemperatureConfirmView.as_view(), name="temperature-confirm"),
    path("temperatures", TemperatureReadingListView.as_view(), name="temperature-list"),
    path("lots/active-search", ActiveLotSearchView.as_view(), name="lots-active-search"),
    path("lots/reconcile-identical", ReconcileIdenticalLotsView.as_view(), name="lots-reconcile-identical"),
    path("labels/profiles", LabelProfileListCreateView.as_view(), name="labels-profile-list-create"),
    path("labels/profiles/<uuid:profile_id>", LabelProfileDetailView.as_view(), name="labels-profile-detail"),
    path("labels/print", LabelPrintView.as_view(), name="labels-print"),
    path("alerts", AlertListView.as_view(), name="alerts-list"),
    path("alerts/<uuid:alert_id>/status", AlertStatusUpdateView.as_view(), name="alerts-status-update"),
    path("reports/lots.csv", LotReportCsvView.as_view(), name="report-lots-csv"),
    path("reports/lots.pdf", LotReportPdfView.as_view(), name="report-lots-pdf"),
    path("reports/temperatures.csv", TemperatureRegisterCsvView.as_view(), name="report-temperatures-csv"),
]
