import { Platform, StyleSheet } from "react-native";

const COLORS = {
  bg: "#f3f6f5",
  surface: "#fcfdfc",
  border: "#c9d7d4",
  borderSoft: "#dbe6e3",
  text: "#173735",
  textMuted: "#486462",
  primary: "#2f7a74",
  primaryPressed: "#256861",
  primarySoft: "#e8f2f0",
  accent: "#2c6ea3",
  warn: "#8a5b18",
  critical: "#a11b2f",
  success: "#216f68",
};

const FONT = Platform.select({ ios: "System", android: "sans-serif", default: "System" });

export const appStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },
  authSafe: { flex: 1, backgroundColor: "#0a1213" },
  container: { padding: 12, gap: 8, paddingBottom: 48 },

  authLanding: {
    flex: 1,
    minHeight: 640,
    justifyContent: "center",
    gap: 10,
    paddingVertical: 22,
  },
  authLogoCard: {
    backgroundColor: "#f7faf9",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#1f3436",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 2,
  },
  authTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#eff8f6",
    textAlign: "center",
    fontFamily: FONT,
    letterSpacing: 0.2,
  },
  authSubtitle: {
    fontSize: 12,
    color: "#a8c2be",
    textAlign: "center",
    fontFamily: FONT,
    marginBottom: 4,
  },
  authCard: {
    backgroundColor: "#0f1d1f",
    borderRadius: 14,
    padding: 12,
    gap: 7,
    borderWidth: 1,
    borderColor: "#264347",
  },
  authCardTitle: { fontSize: 14, fontWeight: "700", color: "#e7f3f1", fontFamily: FONT },
  authInput: {
    borderWidth: 1,
    borderColor: "#35555a",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    minHeight: 40,
    backgroundColor: "#112527",
    color: "#edf7f5",
    fontSize: 12,
    fontFamily: FONT,
  },
  authButton: {
    backgroundColor: "#2f7a74",
    paddingVertical: 10,
    borderRadius: 10,
    minHeight: 40,
    justifyContent: "center",
    marginTop: 2,
  },
  authButtonPressed: { backgroundColor: "#266761" },
  authButtonText: { color: "#ffffff", textAlign: "center", fontWeight: "700", fontSize: 12, fontFamily: FONT },
  authTokenPreview: { color: "#a8c2be", fontSize: 10, fontFamily: FONT },

  title: { fontSize: 21, fontWeight: "700", color: COLORS.text, fontFamily: FONT },
  subtitle: { fontSize: 11, color: COLORS.textMuted, fontFamily: FONT, lineHeight: 15 },

  tabsRow: { flexDirection: "row", gap: 6, flexWrap: "wrap", marginBottom: 4 },
  tabButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    minHeight: 40,
    justifyContent: "center",
  },
  tabButtonPressed: { backgroundColor: COLORS.primarySoft, borderColor: "#a8c1bd" },
  tabButtonActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  tabText: { color: COLORS.textMuted, fontWeight: "600", fontSize: 11, fontFamily: FONT, lineHeight: 14 },
  tabTextActive: { color: "#ffffff" },

  chipWithDelete: { flexDirection: "row", alignItems: "center", gap: 4 },
  chipDelete: {
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  chipDeleteText: { color: COLORS.critical, fontWeight: "700", fontSize: 11, fontFamily: FONT },

  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    shadowColor: "#0f2524",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },

  label: { fontSize: 10, fontWeight: "700", color: COLORS.textMuted, marginTop: 4, fontFamily: FONT },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 40,
    backgroundColor: "#ffffff",
    fontSize: 12,
    color: COLORS.text,
    fontFamily: FONT,
  },

  button: {
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    borderRadius: 9,
    marginTop: 6,
    minHeight: 40,
    justifyContent: "center",
  },
  buttonPressed: { backgroundColor: COLORS.primaryPressed },
  buttonText: { color: "white", textAlign: "center", fontWeight: "600", fontSize: 12, fontFamily: FONT },

  buttonSecondary: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: 10,
    borderRadius: 9,
    minHeight: 40,
    justifyContent: "center",
  },
  buttonSecondaryPressed: { backgroundColor: COLORS.primarySoft },
  buttonSecondaryText: { color: COLORS.primary, textAlign: "center", fontWeight: "600", fontSize: 12, fontFamily: FONT },

  sectionTitle: { fontSize: 14, fontWeight: "800", color: COLORS.text, fontFamily: FONT, marginBottom: 2 },
  infoText: { color: COLORS.primary, fontSize: 11, fontWeight: "600", fontFamily: FONT },

  linkButton: { paddingVertical: 4 },
  linkText: { color: COLORS.accent, fontWeight: "600", fontSize: 11, fontFamily: FONT },

  draftRow: { borderTopWidth: 1, borderTopColor: "#e8efed", paddingTop: 7, gap: 3 },

  smallButton: { backgroundColor: "#3e617b", paddingVertical: 8, borderRadius: 7, alignItems: "center" },
  smallButtonText: { color: "white", fontWeight: "600", fontSize: 11, fontFamily: FONT },

  error: { color: COLORS.critical, fontWeight: "600", fontSize: 11, fontFamily: FONT },
  tokenPreview: { color: COLORS.textMuted, fontSize: 10, fontFamily: FONT, lineHeight: 13 },
  warn: { color: COLORS.warn, fontSize: 11, fontFamily: FONT },
  critical: { color: COLORS.critical, fontSize: 11, fontWeight: "700", fontFamily: FONT },
  success: { color: COLORS.success, fontWeight: "600", fontSize: 11, fontFamily: FONT },

  cameraPreview: {
    width: "100%",
    height: 320,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#0b0f10",
  },

  bottomNavWrap: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: Platform.select({ android: 56, ios: 10, default: 14 }),
    alignItems: "center",
  },
  bottomNavHint: {
    marginBottom: 5,
    backgroundColor: COLORS.text,
    color: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: "hidden",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: FONT,
  },
  bottomNav: {
    width: "100%",
    backgroundColor: "#fdfefe",
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 13,
    paddingVertical: 5,
    paddingHorizontal: 7,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 5,
    shadowColor: "#0f2524",
    shadowOpacity: 0.1,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  bottomNavItem: {
    flex: 1,
    borderRadius: 9,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
  },
  bottomNavItemActive: {
    backgroundColor: COLORS.primary,
  },
  bottomNavIcon: {
    fontSize: 23,
    marginBottom: 0,
  },
  bottomNavIconActive: {
    color: "#ffffff",
  },
  bottomNavText: { display: "none" },
  bottomNavTextActive: { display: "none" },
});
