import { StyleSheet } from "react-native";

export const appStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f7f8" },
  container: { padding: 16, gap: 12, paddingBottom: 36 },
  title: { fontSize: 28, fontWeight: "700", color: "#0f2e2e" },
  subtitle: { fontSize: 14, color: "#496464" },
  tabsRow: { flexDirection: "row", gap: 8, flexWrap: "wrap", marginBottom: 6 },
  tabButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#b8cbcb",
    backgroundColor: "#fff",
    minHeight: 44,
    justifyContent: "center",
  },
  tabButtonPressed: { backgroundColor: "#edf5f5", borderColor: "#8cb4b1" },
  tabButtonActive: { backgroundColor: "#0c6b65", borderColor: "#0c6b65" },
  tabText: { color: "#37595c", fontWeight: "600" },
  tabTextActive: { color: "#fff" },
  chipWithDelete: { flexDirection: "row", alignItems: "center", gap: 4 },
  chipDelete: {
    borderWidth: 1,
    borderColor: "#c9d9d9",
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  chipDeleteText: { color: "#b00020", fontWeight: "700" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: "#d8e2e2",
    shadowColor: "#082423",
    shadowOpacity: 0.08,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  label: { fontSize: 12, fontWeight: "700", color: "#2a4a4d", marginTop: 6 },
  input: { borderWidth: 1, borderColor: "#b8cbcb", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 10, minHeight: 44 },
  button: { backgroundColor: "#0c6b65", paddingVertical: 12, borderRadius: 10, marginTop: 8, minHeight: 44, justifyContent: "center" },
  buttonPressed: { backgroundColor: "#0a5d58" },
  buttonText: { color: "white", textAlign: "center", fontWeight: "600" },
  buttonSecondary: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#0c6b65",
    paddingVertical: 12,
    borderRadius: 10,
    minHeight: 44,
    justifyContent: "center",
  },
  buttonSecondaryPressed: { backgroundColor: "#edf5f5" },
  buttonSecondaryText: { color: "#0c6b65", textAlign: "center", fontWeight: "600" },
  sectionTitle: { fontSize: 17, fontWeight: "800", color: "#0f2e2e" },
  infoText: { color: "#0c6b65", fontSize: 12, fontWeight: "600" },
  linkButton: { paddingVertical: 6 },
  linkText: { color: "#0e6eb8", fontWeight: "600" },
  draftRow: { borderTopWidth: 1, borderTopColor: "#ecf1f1", paddingTop: 8, gap: 4 },
  smallButton: { backgroundColor: "#1635a6", paddingVertical: 8, borderRadius: 6, alignItems: "center" },
  smallButtonText: { color: "white", fontWeight: "600" },
  error: { color: "#b00020", fontWeight: "600" },
  tokenPreview: { color: "#37595c", fontSize: 12 },
  warn: { color: "#9a5b00", fontSize: 12 },
  critical: { color: "#b00020", fontSize: 12, fontWeight: "700" },
  success: { color: "#0c6b65", fontWeight: "600" },
  cameraPreview: {
    width: "100%",
    height: 360,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#0b0f10",
  },
});
