# Generated by Django 5.2.11 on 2026-02-21 07:45

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProduct',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(default='fr', max_length=12)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('storage_profiles', models.JSONField(blank=True, default=list)),
                ('label_hints', models.JSONField(blank=True, null=True)),
                ('source_app', models.CharField(default='fiches-recettes', max_length=64)),
                ('export_version', models.CharField(default='1.1', max_length=16)),
                ('updated_at_source', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_lot_code', models.CharField(max_length=64, unique=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_lot_code', models.CharField(blank=True, default='', max_length=128)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=32)),
                ('received_date', models.DateField(default=datetime.date.today)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('dlc_date', models.DateField(blank=True, null=True)),
                ('category_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('TRANSFORMED', 'TRANSFORMED'), ('CONSUMED', 'CONSUMED'), ('DISCARDED', 'DISCARDED')], default='DRAFT', max_length=24)),
                ('ai_payload', models.JSONField(blank=True, default=dict)),
                ('ai_suggested', models.BooleanField(default=False)),
                ('validated_by', models.CharField(blank=True, default='', max_length=64)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiche_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.ficheproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('PHOTO_LABEL', 'PHOTO_LABEL'), ('PHOTO_PRODUCT', 'PHOTO_PRODUCT'), ('DELIVERY_NOTE', 'DELIVERY_NOTE'), ('INVOICE', 'INVOICE')], max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_link', models.URLField(blank=True, default='')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.lot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('EXPIRY_D3', 'EXPIRY_D3'), ('EXPIRY_D2', 'EXPIRY_D2'), ('EXPIRY_D1', 'EXPIRY_D1'), ('EXPIRED', 'EXPIRED')], max_length=32)),
                ('trigger_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('ACKED', 'ACKED'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.lot')),
            ],
        ),
        migrations.CreateModel(
            name='OcrJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=16)),
                ('provider', models.CharField(default='claude', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='core.asset')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_jobs', to='core.lot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('record_hash', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.site')),
            ],
            options={
                'ordering': ['happened_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_text', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiche_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.ficheproduct')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.site')),
            ],
            options={
                'unique_together': {('site', 'fiche_product', 'alias_text', 'supplier_name')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('CHEF', 'CHEF'), ('OPERATOR', 'OPERATOR'), ('AUDITOR', 'AUDITOR')], default='OPERATOR', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_memberships', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.site')),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
