# Generated by Django 5.2.11 on 2026-02-21 08:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'CREATED'), ('TRANSFORMED', 'TRANSFORMED'), ('FREEZING', 'FREEZING'), ('THAWING', 'THAWING'), ('OPENED', 'OPENED'), ('VACUUM_PACKING', 'VACUUM_PACKING'), ('SOUS_VIDE_COOK', 'SOUS_VIDE_COOK')], max_length=32)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_events', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotTransformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'CREATED'), ('TRANSFORMED', 'TRANSFORMED'), ('FREEZING', 'FREEZING'), ('THAWING', 'THAWING'), ('OPENED', 'OPENED'), ('VACUUM_PACKING', 'VACUUM_PACKING'), ('SOUS_VIDE_COOK', 'SOUS_VIDE_COOK')], max_length=32)),
                ('input_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('output_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('new_dlc_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transformation', to='core.lotevent')),
                ('from_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations_from', to='core.lot')),
                ('to_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations_to', to='core.lot')),
            ],
        ),
    ]
