# Generated by Django 5.2.11 on 2026-02-27 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lotevent_lottransformation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotDocumentMatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("document_type", models.CharField(help_text="DELIVERY_NOTE|INVOICE|GOODS_RECEIPT", max_length=24)),
                ("document_number", models.CharField(max_length=128)),
                ("line_ref", models.CharField(blank=True, default="", max_length=128)),
                ("supplier_product_id", models.CharField(blank=True, default="", max_length=128)),
                ("qty_value", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("qty_unit", models.CharField(blank=True, default="", max_length=16)),
                ("status", models.CharField(choices=[("CONFIRMED", "CONFIRMED"), ("REJECTED", "REJECTED")], default="CONFIRMED", max_length=16)),
                ("rationale", models.JSONField(blank=True, default=dict)),
                ("confirmed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lot_document_matches", to=settings.AUTH_USER_MODEL)),
                ("lot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_matches", to="core.lot")),
            ],
            options={
                "unique_together": {("lot", "document_type", "document_number", "line_ref")},
            },
        ),
    ]
