# Generated by Django 5.2.11 on 2026-03-04 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lotdocumentmatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_type", models.CharField(choices=[("FRIDGE", "FRIDGE"), ("FREEZER", "FREEZER"), ("COLD_ROOM", "COLD_ROOM"), ("OTHER", "OTHER")], default="OTHER", max_length=24)),
                ("device_label", models.CharField(blank=True, default="", max_length=120)),
                ("temperature_celsius", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(default="C", max_length=4)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(default="OCR_PHOTO", max_length=24)),
                ("ocr_provider", models.CharField(blank=True, default="", max_length=32)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("ocr_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="temperature_readings", to=settings.AUTH_USER_MODEL)),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="temperature_readings", to="core.site")),
            ],
            options={
                "ordering": ["-observed_at", "-created_at"],
            },
        ),
    ]
