# Generated by Django 5.2.11 on 2026-03-04 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_temperaturereading"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColdSector",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cold_sectors", to="core.site")),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("site", "name")},
            },
        ),
        migrations.CreateModel(
            name="ColdPoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("device_type", models.CharField(choices=[("FRIDGE", "FRIDGE"), ("FREEZER", "FREEZER"), ("COLD_ROOM", "COLD_ROOM"), ("OTHER", "OTHER")], default="OTHER", max_length=24)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("min_temp_celsius", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_temp_celsius", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sector", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cold_points", to="core.coldsector")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cold_points", to="core.site")),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("sector", "name")},
            },
        ),
        migrations.CreateModel(
            name="TemperatureRoute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_temperature_routes", to=settings.AUTH_USER_MODEL)),
                ("sector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="temperature_routes", to="core.coldsector")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="temperature_routes", to="core.site")),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("site", "name")},
            },
        ),
        migrations.CreateModel(
            name="TemperatureRouteStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("step_order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cold_point", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="route_steps", to="core.coldpoint")),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="core.temperatureroute")),
            ],
            options={
                "ordering": ["step_order", "created_at"],
                "unique_together": {("route", "step_order"), ("route", "cold_point")},
            },
        ),
        migrations.AddField(
            model_name="temperaturereading",
            name="cold_point",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="temperature_readings", to="core.coldpoint"),
        ),
    ]
