# Generated by Django 5.2.11 on 2026-03-05 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_registers_for_existing_sectors(apps, schema_editor):
    ColdSector = apps.get_model("core", "ColdSector")
    TemperatureRegister = apps.get_model("core", "TemperatureRegister")
    for sector in ColdSector.objects.all().iterator():
        TemperatureRegister.objects.get_or_create(
            sector=sector,
            defaults={"site_id": sector.site_id, "name": sector.name},
        )


def link_existing_readings_to_registers(apps, schema_editor):
    TemperatureReading = apps.get_model("core", "TemperatureReading")
    TemperatureRegister = apps.get_model("core", "TemperatureRegister")
    for reading in TemperatureReading.objects.filter(cold_point_id__isnull=False).select_related("cold_point__sector"):
        sector = getattr(getattr(reading, "cold_point", None), "sector", None)
        if not sector:
            continue
        register = TemperatureRegister.objects.filter(sector=sector).first()
        if not register:
            continue
        reading.register_id = register.id
        reading.save(update_fields=["register"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_coldchain_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemperatureRegister",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sector", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="temperature_register", to="core.coldsector")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="temperature_registers", to="core.site")),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("site", "name")},
            },
        ),
        migrations.AddField(
            model_name="temperaturereading",
            name="reference_temperature_celsius",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="temperaturereading",
            name="register",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="temperature_readings", to="core.temperatureregister"),
        ),
        migrations.RunPython(create_registers_for_existing_sectors, migrations.RunPython.noop),
        migrations.RunPython(link_existing_readings_to_registers, migrations.RunPython.noop),
    ]
