# Generated by Django 5.2.11 on 2026-03-06 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_temperature_register_and_reading_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('template_type', models.CharField(choices=[('RAW_MATERIAL', 'RAW_MATERIAL'), ('PREPARATION', 'PREPARATION'), ('TRANSFORMATION', 'TRANSFORMATION')], default='PREPARATION', max_length=24)),
                ('shelf_life_value', models.PositiveIntegerField(default=1)),
                ('shelf_life_unit', models.CharField(choices=[('hours', 'hours'), ('days', 'days'), ('months', 'months')], default='days', max_length=12)),
                ('packaging', models.CharField(blank=True, default='', max_length=64)),
                ('storage_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('show_internal_lot', models.BooleanField(default=True)),
                ('show_supplier_lot', models.BooleanField(default=False)),
                ('allergen_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_profiles', to='core.site')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LabelPrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_internal_code', models.CharField(blank=True, default='', max_length=64)),
                ('production_date', models.DateField()),
                ('dlc_date', models.DateField()),
                ('copies', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_print_jobs', to='core.lot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_print_jobs', to='core.site')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='core.labelprofile')),
            ],
        ),
    ]
