# Generated by Django 5.2.11 on 2026-03-12 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_labelprofile_labelprintjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coldpoint',
            name='external_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='coldpoint',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coldsector',
            name='external_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='coldsector',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='corrected_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'pending'), ('validated', 'validated'), ('rejected', 'rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='HaccpSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('label_print', 'label_print'), ('temperature_register', 'temperature_register'), ('cleaning', 'cleaning')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('equipment_type', models.CharField(blank=True, choices=[('FRIDGE', 'FRIDGE'), ('FREEZER', 'FREEZER'), ('COLD_ROOM', 'COLD_ROOM'), ('OTHER', 'OTHER')], default='', max_length=24)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('done', 'done'), ('skipped', 'skipped'), ('cancelled', 'cancelled')], default='planned', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cold_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haccp_schedules', to='core.coldpoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_haccp_schedules', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haccp_schedules', to='core.coldsector')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haccp_schedules', to='core.site')),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
    ]
