# Generated by Django 5.2.11 on 2026-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_labelprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_reason',
            field=models.CharField(blank=True, choices=[('CONSUMED', 'CONSUMED'), ('DISCARDED', 'DISCARDED'), ('TRANSFORMED', 'TRANSFORMED')], default='', max_length=24),
        ),
    ]
